version: '3.8'

services:
    # Serviço do Laravel
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - db
        ports:
            - "9000:9000"

    # Serviço MySQL
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: gestaoTarefas
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - "3306:3306"

    # Serviço do Nginx
    web:
        image: nginx:alpine
        container_name: nginx_web
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - "80:80"
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network:
        driver: bridge

volumes:
    dbdata:
