version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=gestaoTarefas
            - DB_USERNAME=root
            - DB_PASSWORD=

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: gestaoTarefas
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
